### ISSUE TITLE
Does v0.4.5 support using STAR as aligner ?

### ISSUE THREAD

**Issue by altairwei** [konrad/READemption#12]
I looked through the source code of READemption, and found some flags in `bin/reademption` : 

```python
    read_aligning_parser.add_argument(
        "--STAR_bin", default="STAR",
        help="STAR's binary path (default 'STAR').")
```

So, I guess that v0.4.5~v0.4.x would support STAR, is that right ? 

I'm really not familiar with segemehl and cannot distinguish the differences between segemehl and STAR/HISAT2 . 

I'm glad to hearing this news. Thank you !

**Comment by Tillsa** [comment]
Using STAR with READemption is still under development and hasn't been tested yet. That's why I would recommend using segemehl right now. segemehl is slower than STAR but the mapping accuracy is similar. You can checkout this page where different mappers are being compared: http://www.ecseq.com/support/benchmark.html.

**Comment by altairwei** [comment]
> Using STAR with READemption is still under development and hasn't been tested yet. That's why I would recommend using segemehl right now. segemehl is slower than STAR but the mapping accuracy is similar. You can checkout this page where different mappers are being compared: http://www.ecseq.com/support/benchmark.html.

Thank you very much !
